package it.univaq.disim.isp.studiomedico.domain;

public enum Specializzazione {
FISIOTERAPIA,
NUTRIZIONISTA,
CARDIOLOGIA,
SENOLOGIA,
OTORINOLARINGOIATRIA,
ORTOPEDIA,
UROLOGIA,
NEUROLOGIA,
GASTROENTEROLOGIA,
ONCOLOGIA,
NEUROCHIRURGIA,
MEDICINAINTERNA,
GINECOLOGIA,
PSICOLOGIA,
CHIRURGIAVASCOLARE,
OSTETRICIA,
ANDROLOGIA,
TRAUMATOLOGIA,
}
