package it.univaq.disim.isp.studiomedico.domain;

public enum TipologiaVisita {
LASERTERAPIA,
ULTRASUONOTERAPIA,
TECARTERTERAPIA,
RIABILITAZIONEPOSTURALE,
VALUTAZIONE,
CHINESITERAPIA,
ELETTROTERAPIA,
LINFODRENAGGIO,
VISITASPECIALISTICA,
ECOCARDIOGRAMMA,
ECG,ECHHOLTER24ORE,HOLTERPRESSORIO,ECGDASFORZO,
ESAMEAUDIOMETRICO,FIBROLARINGOSCOPIA,ESAMEDESTIBOLARE,
ECOGRAFIA,
ELETTROMIOGRAFIA,
VISITAGASTROENTEROLOGICA,
VISITAPROCTOLOGICA,IDROCOLONTERAPIA,BREATHTEST,
VISITAOSTETRICA,VISITAGINECOLOGICA,ECOGRAFIAGINECOLOGICA,PAPTEST,
ECOCOLORDOPPLER,
}
